// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDC7RfPDPCH011KhEyX55em-vgGHjbY2Q',
    appId: '1:156381992021:web:736f71989bd940023630dc',
    messagingSenderId: '156381992021',
    projectId: 'warmthfromafar-2caaa',
    authDomain: 'warmthfromafar-2caaa.firebaseapp.com',
    storageBucket: 'warmthfromafar-2caaa.firebasestorage.app',
    measurementId: 'G-4T2R8GPP9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wj9fU-86ez0JuwAvpoOxkcjzC8glq1E',
    appId: '1:156381992021:android:12b3cb8e6c19f6b63630dc',
    messagingSenderId: '156381992021',
    projectId: 'warmthfromafar-2caaa',
    storageBucket: 'warmthfromafar-2caaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwgtesOzOutEcBA3uXjE3B6eJUQjEfAY',
    appId: '1:156381992021:ios:4aca622048dd84023630dc',
    messagingSenderId: '156381992021',
    projectId: 'warmthfromafar-2caaa',
    storageBucket: 'warmthfromafar-2caaa.firebasestorage.app',
    iosBundleId: 'com.example.warmthFromAfar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZwgtesOzOutEcBA3uXjE3B6eJUQjEfAY',
    appId: '1:156381992021:ios:4aca622048dd84023630dc',
    messagingSenderId: '156381992021',
    projectId: 'warmthfromafar-2caaa',
    storageBucket: 'warmthfromafar-2caaa.firebasestorage.app',
    iosBundleId: 'com.example.warmthFromAfar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDC7RfPDPCH011KhEyX55em-vgGHjbY2Q',
    appId: '1:156381992021:web:b12c867e471c7f8d3630dc',
    messagingSenderId: '156381992021',
    projectId: 'warmthfromafar-2caaa',
    authDomain: 'warmthfromafar-2caaa.firebaseapp.com',
    storageBucket: 'warmthfromafar-2caaa.firebasestorage.app',
    measurementId: 'G-X628NJG39B',
  );
}
